server:
  port: 8080

  servlet:
    context-path: /

spring:
  datasource:
    username: tos
    password: 13211333153
    url: jdbc:mysql://39.100.71.212:3306/tos?characterEncoding=utf-8&useSSl=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    #监控统计拦截的filters
    filters: stat,wall,log4j


  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL55Dialect

  redis:
    host: 39.100.71.212
    port: 6379
    password: 13211333153


token:
  #redis默认过期时间（2小时)
  expirationMilliSeconds: 7200

jwt:
  config:
    key: "123456"
    ttl: 7200000

wx:
  miniapp:
    appid: wxd8b73bbb2d4cc8ab
    secret: 1a43e7c8f76e81b7568c43c07f976aa4